#!/bin/bash


for dir in `ls /home/Aditya/BDE`; do
        cd $dir;
        values="$(for file in *;do
        grep "SCF Done" $file | tail --lines=1| awk '{print $5}' ;
        done)";

        index="$(for i in ${values[@]}; do echo $i; done | sort -g | head -1)";

        echo $index;

        cd ../;

 done
